import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { routeSales } from '../skills/sales-orchestration/scripts/route-sales.mjs';
const host = () => ({ assembly: 'real-estate', department: 'sales', org_id: 'org-a', project_id: 'project-a', current: true, authorized: true, core_version: '0.5.3', source_map_current: true, source_map_ref: 'source-map/v2', provider_ready: { 'woia-sales-follow-up': true, 'woia-sales-pipeline': true, 'woia-sales-lead-qualification': true }, accepted_transition: true });
const req = () => ({ org_id: 'org-a', project_id: 'project-a', route: 'follow-up', action: 'draft' });
test('RE follow-up delegates only a draft and communication owner', () => assert.deepEqual(routeSales(req(),host()), { provider: 'woia-sales-follow-up', action:'draft', communication_owner:'customer-service', effect_execution:false }));
test('RE follow-up plan remains available', () => assert.equal(routeSales({...req(),action:'plan'},host()).effect_execution,false));
for (const action of ['send','schedule','negotiate','payment.execute','confirm']) test(`RE cannot perform ${action}`,()=>assert.throws(()=>routeSales({...req(),action},host())));
test('request assembly flag cannot enable legacy send',()=>assert.throws(()=>routeSales({...req(),assembly:'generic',action:'send'},host()),/OWNER/));
test('trusted generic assembly preserves existing v1 route',()=>assert.equal(routeSales({...req(),action:'send'},{...host(),assembly:'generic'}).contract,'existing-v1'));
test('qualified later stable Core satisfies minimum version',()=>assert.equal(routeSales(req(),{...host(),core_version:'1.0.0'}).effect_execution,false));
for (const patch of [{org_id:'other'},{project_id:'other'}]) test(`scope mismatch ${JSON.stringify(patch)}`,()=>assert.throws(()=>routeSales({...req(),...patch},host()),/SCOPE_MISMATCH/));
for (const patch of [{current:false},{authorized:false},{assembly:undefined},{core_version:'0.5.2'},{source_map_current:false},{provider_ready:{}}]) test(`host fail closed ${JSON.stringify(patch)}`,()=>assert.throws(()=>routeSales(req(),{...host(),...patch})));
test('unknown prior effect requires reconciliation',()=>assert.throws(()=>routeSales({...req(),effect_state:'UNKNOWN'},host()),/RECONCILE/));
test('prototype route is rejected',()=>assert.throws(()=>routeSales({...req(),route:'toString'},host()),/UNKNOWN_ROUTE/));
test('typed Opportunity proposal is not accepted business fact',()=>{const r=routeSales({...req(),route:'pipeline-change',subject_kind:'Opportunity',subject_ref:'opportunity/1'},host());assert.equal(r.competent_acceptance_granted,false);assert.equal(r.effect_execution,false);});
test('customer record cannot impersonate Opportunity',()=>assert.throws(()=>routeSales({...req(),route:'pipeline-change',subject_kind:'Customer',subject_ref:'customer/1'},host()),/TYPED/));
test('pipeline requires competent transition acceptance',()=>assert.throws(()=>routeSales({...req(),route:'pipeline-change',subject_kind:'Opportunity',subject_ref:'opportunity/1'},{...host(),accepted_transition:false}),/COMPETENT/));
test('pipeline cannot accept domain facts',()=>assert.throws(()=>routeSales({...req(),route:'pipeline-change',subject_kind:'Opportunity',subject_ref:'opportunity/1',domain_fact_acceptance:true},host()),/NOT_DOMAIN/));
test('qualification never grants acceptance',()=>assert.equal(routeSales({...req(),route:'qualification'},host()).competent_acceptance_granted,false));
test('manifest Core requirement and versions align',()=>{const j=p=>JSON.parse(readFileSync(p,'utf8'));assert.equal(j('plugin.json').version,'0.5.1');assert.equal(j('package.json').version,'0.5.1');assert.equal(j('dev.woia/manifest.json').version,'0.5.1');assert.equal(j('dev.woia/manifest.json').requires_plugins[0].minimum_version,'0.5.3');for(const c of ['lead-qualification','follow-up','pipeline']){const contract=j(`contracts/${c}.json`);assert.equal(contract.contract_version,'0.5.0');assert.equal(contract.id,`${c}/v1`);}});
